development:
  adapter: postgresql
  database: personal_site_development
  pool: 5
  host: localhost
  username: gregorygrillone

test:
  adapter: postgresql
  database: personal_site_development
  pool: 5